#!/usr/bin/env python3
"""
ops/scripts/brief_writer.py — Agent Brief Auto-Writer (B2)
Generates per-dept BRIEF_<date>.md from task_backlog.json.
Triggered by: aos.py corp dispatch

Usage:
  python ops/scripts/brief_writer.py              # Write briefs for all depts
  python ops/scripts/brief_writer.py engineering  # Write for 1 dept only
"""
import json
import sys
from pathlib import Path
from datetime import datetime

ROOT     = Path(__file__).parent.parent.parent
BACKLOG  = ROOT / "brain" / "shared-context" / "corp" / "task_backlog.json"
DEPTS    = ROOT / "corp" / "departments"

def write_brief(dept_name: str, tasks: list, date: str) -> Path:
    brief_dir = DEPTS / dept_name / "briefs"
    brief_dir.mkdir(parents=True, exist_ok=True)
    brief_file = brief_dir / f"BRIEF_{date}.md"

    open_tasks = [t for t in tasks if t.get("status") != "DONE"]
    done_tasks = [t for t in tasks if t.get("status") == "DONE"]

    lines = [
        f"# BRIEF — {dept_name.upper().replace('_', ' ')} — {date}",
        f"*Auto-generated by brief_writer.py | {datetime.now().strftime('%H:%M:%S')}*",
        f"*Trigger: aos.py corp dispatch*",
        "",
        f"## Tasks This Cycle ({len(open_tasks)} open, {len(done_tasks)} done)",
        "",
        "| ID | Task | Priority | Assignee | Due | Status |",
        "|----|------|----------|----------|-----|--------|",
    ]

    for t in open_tasks:
        lines.append(f"| {t.get('id','?')} | {t.get('title','?')[:50]} | {t.get('priority','?')} | {t.get('assignee','?')} | {t.get('due','?')} | {t.get('status','OPEN')} |")

    if done_tasks:
        lines += ["", "### Completed", ""]
        for t in done_tasks:
            lines.append(f"- ✅ [{t.get('id')}] {t.get('title','?')[:50]}")

    lines += [
        "",
        "## Agent Notes",
        "*[Agent fills in: blockers, insights, escalations]*",
        "",
        "## Escalations",
        "*None* (or list items requiring CEO attention)",
        "",
        f"---",
        f"*Brief v1.0 | {dept_name} | {date}*",
    ]

    brief_file.write_text("\n".join(lines), encoding="utf-8")
    return brief_file

def main():
    if not BACKLOG.exists():
        print(f"[ERR] task_backlog.json not found: {BACKLOG}")
        return

    backlog = json.loads(BACKLOG.read_text(encoding="utf-8"))
    date = datetime.now().strftime("%Y-%m-%d")

    target = sys.argv[1].lower() if len(sys.argv) > 1 else None
    written = 0

    for dept, tasks in backlog.items():
        if dept.startswith("_"):  # skip _meta, _template
            continue
        if target and target != dept:
            continue
        if not isinstance(tasks, list) or not tasks:
            continue

        brief_file = write_brief(dept, tasks, date)
        print(f"  ✅ {dept}: {brief_file.relative_to(ROOT)}")
        written += 1

    print(f"\nDone — {written} dept brief(s) written for {date}")

if __name__ == "__main__":
    main()
