#!/usr/bin/env python3
"""
ops/scripts/ki_indexer.py — KI Auto-Index Generator (B6)
Scans brain/knowledge/notes/ and generates brain/knowledge/KI_INDEX.md

Usage:
  python ops/scripts/ki_indexer.py           # Generate KI_INDEX.md
  python ops/scripts/ki_indexer.py --watch   # Re-generate on file change
"""
import os
import re
from pathlib import Path
from datetime import datetime

ROOT      = Path(__file__).parent.parent.parent
NOTES_DIR = ROOT / "brain" / "knowledge" / "notes"
INDEX_OUT = ROOT / "brain" / "knowledge" / "KI_INDEX.md"

def parse_ki_note(path: Path) -> dict:
    """Extract metadata from a KI note file."""
    try:
        content = path.read_text(encoding="utf-8", errors="ignore")
        lines = content.splitlines()

        # Title (first # heading)
        title = next((l.lstrip("#").strip() for l in lines if l.startswith("#")), path.stem)

        # Date from filename: KI-TOPIC-2026-03-24.md
        date_match = re.search(r"(\d{4}-\d{2}-\d{2})", path.name)
        date = date_match.group(1) if date_match else "unknown"

        # Tags/type from content
        topic = path.stem.replace("KI-", "").replace("-", " ").strip()
        value_type = "unknown"
        for line in lines[:20]:
            if "value_type:" in line.lower():
                value_type = line.split(":", 1)[-1].strip()
                break
            if any(k in line.lower() for k in ["score:", "tier:", "type:"]):
                value_type = line.split(":", 1)[-1].strip()[:30]
                break

        # Source
        source = "internal"
        for line in lines[:30]:
            if "source:" in line.lower() or "http" in line.lower() or "github" in line.lower():
                source_match = re.search(r"https?://[^\s\)]+", line)
                if source_match:
                    source = source_match.group(0)[:50]
                    break

        return {
            "file": path.name,
            "title": title[:60],
            "date": date,
            "topic": topic[:40],
            "value_type": value_type[:20],
            "source": source[:50],
            "size": len(content),
        }
    except Exception as e:
        return {"file": path.name, "title": path.stem, "date": "?", "topic": "?", "value_type": "?", "source": "?", "size": 0}

def generate_index():
    if not NOTES_DIR.exists():
        print(f"[SKIP] Notes dir not found: {NOTES_DIR}")
        return

    notes = sorted(NOTES_DIR.glob("*.md"), key=lambda p: p.stat().st_mtime, reverse=True)
    mds   = [p for p in notes if not p.name.startswith("_")]

    rows = []
    for p in mds:
        meta = parse_ki_note(p)
        rows.append(meta)

    now = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    lines = [
        "# 📚 KI Index — Knowledge Items",
        f"*Auto-generated by ki_indexer.py | {now} | {len(rows)} items*",
        f"*Source: brain/knowledge/notes/ | Update: CIV pipeline + manual*",
        "",
        "---",
        "",
        f"| Date | Topic | Title | Value Type | Source | File |",
        f"|------|-------|-------|------------|--------|------|",
    ]
    for r in rows:
        src_display = f"[link]({r['source']})" if r["source"].startswith("http") else r["source"]
        lines.append(f"| {r['date']} | {r['topic']} | {r['title']} | {r['value_type']} | {src_display} | [{r['file']}](notes/{r['file']}) |")

    lines += ["", "---", f"*{len(rows)} knowledge items indexed | Run: python ops/scripts/ki_indexer.py*"]

    INDEX_OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"✅ KI_INDEX.md generated — {len(rows)} items → {INDEX_OUT.relative_to(ROOT)}")
    return rows

if __name__ == "__main__":
    generate_index()
