import os
from datetime import datetime
import json

TARGETS = [
    # (Path, Category, Type)
    (r"<AI_OS_ROOT>\brain\knowledge\repos", "LOCAL_CORE", "REPO"),
    (r"<AI_OS_ROOT>\ecosystem\plugins", "LOCAL_CORE", "PLUGIN"),
    (r"<AI_OS_ROOT>\ecosystem\tools", "LOCAL_CORE", "TOOL"),
    (r"<AI_OS_ROOT>\ecosystem\skills", "LOCAL_CORE", "SKILL"),
    (r"<AI_OS_ROOT>\ecosystem\workforce\subagents", "LOCAL_CORE", "AGENT"),
    (r"<AI_OS_ROOT>\system\security\QUARANTINE\vetted\repos", "LOCAL_CORE", "REPO"),

    (r"<AI_OS_REMOTE_ROOT>\brain\knowledge\repos", "REMOTE_ECOSYSTEM", "REPO"),
    (r"<AI_OS_REMOTE_ROOT>\ecosystem\plugins", "REMOTE_ECOSYSTEM", "PLUGIN"),
    (r"<AI_OS_REMOTE_ROOT>\incoming_repos", "REMOTE_ECOSYSTEM", "REPO"),
    (r"<AI_OS_REMOTE_ROOT>\ui_dashboard", "REMOTE_ECOSYSTEM", "UI_COMPONENT"),
    (r"<AI_OS_REMOTE_ROOT>\telegram_bot", "REMOTE_ECOSYSTEM", "GATEWAY"),
    (r"<AI_OS_REMOTE_ROOT>\routers", "REMOTE_ECOSYSTEM", "ROUTER"),
    (r"<AI_OS_REMOTE_ROOT>\openclaw", "REMOTE_ECOSYSTEM", "OPENCLAW"),
    (r"<AI_OS_REMOTE_ROOT>\taskclaw", "REMOTE_ECOSYSTEM", "OPENCLAW"),
]

REGISTRY_OUT = r"<AI_OS_ROOT>\system\registry\SYSTEM_INDEX.yaml"

def generate_safe_id(name, cat, typ):
    clean = "".join(c if c.isalnum() else "_" for c in name.lower())
    return f"{cat.lower()}_{typ.lower()}_{clean}"

def build_registry():
    entities = []

    for path, cat, typ in TARGETS:
        if not os.path.exists(path):
            continue

        for item in os.listdir(path):
            ipath = os.path.join(path, item)
            if os.path.isdir(ipath):
                e_id = generate_safe_id(item, cat, typ)
                entities.append({
                    "id": e_id,
                    "name": item,
                    "path": ipath,
                    "category": cat,
                    "type": typ
                })

    with open(REGISTRY_OUT, "w", encoding="utf-8") as f:
        f.write("# ==========================================\n")
        f.write("# 🌐 AI OS MASTER REGISTRY (SYSTEM_INDEX)\n")
        f.write("# ==========================================\n")
        f.write("# AUTO-GENERATED BY registry_indexer.py\n")
        f.write(f"# LAST SCAN: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")

        f.write("ai_os_system_index:\n")
        f.write(f"  total_entities: {len(entities)}\n")
        f.write("  entities:\n")

        for e in entities:
            # Escape single quotes in name and path
            name = str(e['name']).replace("'", "''")
            path = str(e['path']).replace("'", "''")
            f.write(f"    - id: '{e['id']}'\n")
            f.write(f"      name: '{name}'\n")
            f.write(f"      path: '{path}'\n")
            f.write(f"      category: '{e['category']}'\n")
            f.write(f"      type: '{e['type']}'\n")

    print(f"[DONE] Indexed {len(entities)} entities into {REGISTRY_OUT}")

if __name__ == "__main__":
    build_registry()
