name: "Python Dependency Submission"

on:
  push:
    branches: ["main"]

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Python Dependency Submission"
        uses: advanced-security/python-dependency-submission-action@v1
        with:
          # Thư mục gốc để quét các thư viện Python
          directory: ./
